const CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const DUPLICATE_EMAIL = 409;
const SERVER_ERROR = 500;

module.exports = {
  CREATED,
  BAD_REQUEST,
  UNAUTHORIZED,
  NOT_FOUND,
  SERVER_ERROR,
  DUPLICATE_EMAIL,
};
